/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetRouteImport } from './routes/target'
import { Route as TaggingRouteImport } from './routes/tagging'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecheckRouteImport } from './routes/recheck'
import { Route as ReadersRouteImport } from './routes/readers'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorOverviewRouteImport } from './routes/supervisor.overview'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsThreatsRouteImport } from './routes/settings.threats'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsMapRouteImport } from './routes/settings.map'
import { Route as SettingsEscalationsRouteImport } from './routes/settings.escalations'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as OpsScanRouteImport } from './routes/ops.scan'
import { Route as DevSimulatorRouteImport } from './routes/dev.simulator'
import { Route as DevLogsRouteImport } from './routes/dev.logs'
import { Route as DevFlagsRouteImport } from './routes/dev.flags'
import { Route as DevEventsRouteImport } from './routes/dev.events'
import { Route as DevDbRouteImport } from './routes/dev.db'
import { Route as DevConsoleRouteImport } from './routes/dev.console'
import { Route as DevApiRouteImport } from './routes/dev.api'
import { Route as AuditLogsRouteImport } from './routes/audit.logs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ApiBagsRfidTrackableRouteImport } from './routes/api.bags.rfid-trackable'
import { Route as ApiBagsPendingTaggingRouteImport } from './routes/api.bags.pending-tagging'
import { Route as ApiAdminUsersRouteImport } from './routes/api.admin.users'
import { Route as ApiXrayBagsBagIdRouteImport } from './routes/api.xray.bags.$bagId'
import { Route as ApiIntegrationsScreeningSuspectEventsRouteImport } from './routes/api.integrations.screening.suspect-events'
import { Route as ApiIntegrationsHbssScansRouteImport } from './routes/api.integrations.hbss.scans'
import { Route as ApiIntegrationsHbssHealthRouteImport } from './routes/api.integrations.hbss.health'
import { Route as ApiDevSimulatorSuspectEventsRouteImport } from './routes/api.dev.simulator.suspect-events'
import { Route as ApiBagsBagIdEncodeTagRouteImport } from './routes/api.bags.$bagId.encode-tag'
import { Route as ApiAdminUsersInvitationsRouteImport } from './routes/api.admin.users.invitations'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api.admin.users.$userId'
import { Route as ApiAdminRolesPermissionsRouteImport } from './routes/api.admin.roles.permissions'
import { Route as ApiXrayBagsBagIdRefreshRouteImport } from './routes/api.xray.bags.$bagId.refresh'
import { Route as ApiAdminUsersUserIdRepairProfileRouteImport } from './routes/api.admin.users.$userId.repair-profile'
import { Route as ApiAdminUsersUserIdActionsRouteImport } from './routes/api.admin.users.$userId.actions'
import { Route as ApiAdminRolesRoleIdPermissionsRouteImport } from './routes/api.admin.roles.$roleId.permissions'

const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)
const TaggingRoute = TaggingRouteImport.update({
  id: '/tagging',
  path: '/tagging',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecheckRoute = RecheckRouteImport.update({
  id: '/recheck',
  path: '/recheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersRoute = ReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorOverviewRoute = SupervisorOverviewRouteImport.update({
  id: '/supervisor/overview',
  path: '/supervisor/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThreatsRoute = SettingsThreatsRouteImport.update({
  id: '/settings/threats',
  path: '/settings/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMapRoute = SettingsMapRouteImport.update({
  id: '/settings/map',
  path: '/settings/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEscalationsRoute = SettingsEscalationsRouteImport.update({
  id: '/settings/escalations',
  path: '/settings/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsScanRoute = OpsScanRouteImport.update({
  id: '/ops/scan',
  path: '/ops/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSimulatorRoute = DevSimulatorRouteImport.update({
  id: '/dev/simulator',
  path: '/dev/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogsRoute = DevLogsRouteImport.update({
  id: '/dev/logs',
  path: '/dev/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFlagsRoute = DevFlagsRouteImport.update({
  id: '/dev/flags',
  path: '/dev/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEventsRoute = DevEventsRouteImport.update({
  id: '/dev/events',
  path: '/dev/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDbRoute = DevDbRouteImport.update({
  id: '/dev/db',
  path: '/dev/db',
  getParentRoute: () => rootRouteImport,
} as any)
const DevConsoleRoute = DevConsoleRouteImport.update({
  id: '/dev/console',
  path: '/dev/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DevApiRoute = DevApiRouteImport.update({
  id: '/dev/api',
  path: '/dev/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit/logs',
  path: '/audit/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBagsRfidTrackableRoute = ApiBagsRfidTrackableRouteImport.update({
  id: '/api/bags/rfid-trackable',
  path: '/api/bags/rfid-trackable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBagsPendingTaggingRoute = ApiBagsPendingTaggingRouteImport.update({
  id: '/api/bags/pending-tagging',
  path: '/api/bags/pending-tagging',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXrayBagsBagIdRoute = ApiXrayBagsBagIdRouteImport.update({
  id: '/api/xray/bags/$bagId',
  path: '/api/xray/bags/$bagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsScreeningSuspectEventsRoute =
  ApiIntegrationsScreeningSuspectEventsRouteImport.update({
    id: '/api/integrations/screening/suspect-events',
    path: '/api/integrations/screening/suspect-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsHbssScansRoute =
  ApiIntegrationsHbssScansRouteImport.update({
    id: '/api/integrations/hbss/scans',
    path: '/api/integrations/hbss/scans',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsHbssHealthRoute =
  ApiIntegrationsHbssHealthRouteImport.update({
    id: '/api/integrations/hbss/health',
    path: '/api/integrations/hbss/health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevSimulatorSuspectEventsRoute =
  ApiDevSimulatorSuspectEventsRouteImport.update({
    id: '/api/dev/simulator/suspect-events',
    path: '/api/dev/simulator/suspect-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBagsBagIdEncodeTagRoute = ApiBagsBagIdEncodeTagRouteImport.update({
  id: '/api/bags/$bagId/encode-tag',
  path: '/api/bags/$bagId/encode-tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersInvitationsRoute =
  ApiAdminUsersInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ApiAdminUsersRoute,
  } as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const ApiAdminRolesPermissionsRoute =
  ApiAdminRolesPermissionsRouteImport.update({
    id: '/api/admin/roles/permissions',
    path: '/api/admin/roles/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrayBagsBagIdRefreshRoute = ApiXrayBagsBagIdRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiXrayBagsBagIdRoute,
} as any)
const ApiAdminUsersUserIdRepairProfileRoute =
  ApiAdminUsersUserIdRepairProfileRouteImport.update({
    id: '/repair-profile',
    path: '/repair-profile',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminUsersUserIdActionsRoute =
  ApiAdminUsersUserIdActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ApiAdminUsersUserIdRoute,
  } as any)
const ApiAdminRolesRoleIdPermissionsRoute =
  ApiAdminRolesRoleIdPermissionsRouteImport.update({
    id: '/api/admin/roles/$roleId/permissions',
    path: '/api/admin/roles/$roleId/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/alarms': typeof AlarmsRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/readers': typeof ReadersRoute
  '/recheck': typeof RecheckRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tagging': typeof TaggingRoute
  '/target': typeof TargetRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/audit/logs': typeof AuditLogsRoute
  '/dev/api': typeof DevApiRoute
  '/dev/console': typeof DevConsoleRoute
  '/dev/db': typeof DevDbRoute
  '/dev/events': typeof DevEventsRoute
  '/dev/flags': typeof DevFlagsRoute
  '/dev/logs': typeof DevLogsRoute
  '/dev/simulator': typeof DevSimulatorRoute
  '/ops/scan': typeof OpsScanRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/escalations': typeof SettingsEscalationsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threats': typeof SettingsThreatsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/supervisor/overview': typeof SupervisorOverviewRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/bags/pending-tagging': typeof ApiBagsPendingTaggingRoute
  '/api/bags/rfid-trackable': typeof ApiBagsRfidTrackableRoute
  '/api/admin/roles/permissions': typeof ApiAdminRolesPermissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/invitations': typeof ApiAdminUsersInvitationsRoute
  '/api/bags/$bagId/encode-tag': typeof ApiBagsBagIdEncodeTagRoute
  '/api/dev/simulator/suspect-events': typeof ApiDevSimulatorSuspectEventsRoute
  '/api/integrations/hbss/health': typeof ApiIntegrationsHbssHealthRoute
  '/api/integrations/hbss/scans': typeof ApiIntegrationsHbssScansRoute
  '/api/integrations/screening/suspect-events': typeof ApiIntegrationsScreeningSuspectEventsRoute
  '/api/xray/bags/$bagId': typeof ApiXrayBagsBagIdRouteWithChildren
  '/api/admin/roles/$roleId/permissions': typeof ApiAdminRolesRoleIdPermissionsRoute
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/repair-profile': typeof ApiAdminUsersUserIdRepairProfileRoute
  '/api/xray/bags/$bagId/refresh': typeof ApiXrayBagsBagIdRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/alarms': typeof AlarmsRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/readers': typeof ReadersRoute
  '/recheck': typeof RecheckRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tagging': typeof TaggingRoute
  '/target': typeof TargetRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/audit/logs': typeof AuditLogsRoute
  '/dev/api': typeof DevApiRoute
  '/dev/console': typeof DevConsoleRoute
  '/dev/db': typeof DevDbRoute
  '/dev/events': typeof DevEventsRoute
  '/dev/flags': typeof DevFlagsRoute
  '/dev/logs': typeof DevLogsRoute
  '/dev/simulator': typeof DevSimulatorRoute
  '/ops/scan': typeof OpsScanRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/escalations': typeof SettingsEscalationsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threats': typeof SettingsThreatsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/supervisor/overview': typeof SupervisorOverviewRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/bags/pending-tagging': typeof ApiBagsPendingTaggingRoute
  '/api/bags/rfid-trackable': typeof ApiBagsRfidTrackableRoute
  '/api/admin/roles/permissions': typeof ApiAdminRolesPermissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/invitations': typeof ApiAdminUsersInvitationsRoute
  '/api/bags/$bagId/encode-tag': typeof ApiBagsBagIdEncodeTagRoute
  '/api/dev/simulator/suspect-events': typeof ApiDevSimulatorSuspectEventsRoute
  '/api/integrations/hbss/health': typeof ApiIntegrationsHbssHealthRoute
  '/api/integrations/hbss/scans': typeof ApiIntegrationsHbssScansRoute
  '/api/integrations/screening/suspect-events': typeof ApiIntegrationsScreeningSuspectEventsRoute
  '/api/xray/bags/$bagId': typeof ApiXrayBagsBagIdRouteWithChildren
  '/api/admin/roles/$roleId/permissions': typeof ApiAdminRolesRoleIdPermissionsRoute
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/repair-profile': typeof ApiAdminUsersUserIdRepairProfileRoute
  '/api/xray/bags/$bagId/refresh': typeof ApiXrayBagsBagIdRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/alarms': typeof AlarmsRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/readers': typeof ReadersRoute
  '/recheck': typeof RecheckRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tagging': typeof TaggingRoute
  '/target': typeof TargetRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/audit/logs': typeof AuditLogsRoute
  '/dev/api': typeof DevApiRoute
  '/dev/console': typeof DevConsoleRoute
  '/dev/db': typeof DevDbRoute
  '/dev/events': typeof DevEventsRoute
  '/dev/flags': typeof DevFlagsRoute
  '/dev/logs': typeof DevLogsRoute
  '/dev/simulator': typeof DevSimulatorRoute
  '/ops/scan': typeof OpsScanRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/escalations': typeof SettingsEscalationsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threats': typeof SettingsThreatsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/supervisor/overview': typeof SupervisorOverviewRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/bags/pending-tagging': typeof ApiBagsPendingTaggingRoute
  '/api/bags/rfid-trackable': typeof ApiBagsRfidTrackableRoute
  '/api/admin/roles/permissions': typeof ApiAdminRolesPermissionsRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRouteWithChildren
  '/api/admin/users/invitations': typeof ApiAdminUsersInvitationsRoute
  '/api/bags/$bagId/encode-tag': typeof ApiBagsBagIdEncodeTagRoute
  '/api/dev/simulator/suspect-events': typeof ApiDevSimulatorSuspectEventsRoute
  '/api/integrations/hbss/health': typeof ApiIntegrationsHbssHealthRoute
  '/api/integrations/hbss/scans': typeof ApiIntegrationsHbssScansRoute
  '/api/integrations/screening/suspect-events': typeof ApiIntegrationsScreeningSuspectEventsRoute
  '/api/xray/bags/$bagId': typeof ApiXrayBagsBagIdRouteWithChildren
  '/api/admin/roles/$roleId/permissions': typeof ApiAdminRolesRoleIdPermissionsRoute
  '/api/admin/users/$userId/actions': typeof ApiAdminUsersUserIdActionsRoute
  '/api/admin/users/$userId/repair-profile': typeof ApiAdminUsersUserIdRepairProfileRoute
  '/api/xray/bags/$bagId/refresh': typeof ApiXrayBagsBagIdRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/alarms'
    | '/change-password'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/map'
    | '/readers'
    | '/recheck'
    | '/register'
    | '/reports'
    | '/simulator'
    | '/tagging'
    | '/target'
    | '/admin/dashboard'
    | '/audit/logs'
    | '/dev/api'
    | '/dev/console'
    | '/dev/db'
    | '/dev/events'
    | '/dev/flags'
    | '/dev/logs'
    | '/dev/simulator'
    | '/ops/scan'
    | '/settings/audit'
    | '/settings/escalations'
    | '/settings/map'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/threats'
    | '/settings/users'
    | '/supervisor/overview'
    | '/api/admin/users'
    | '/api/bags/pending-tagging'
    | '/api/bags/rfid-trackable'
    | '/api/admin/roles/permissions'
    | '/api/admin/users/$userId'
    | '/api/admin/users/invitations'
    | '/api/bags/$bagId/encode-tag'
    | '/api/dev/simulator/suspect-events'
    | '/api/integrations/hbss/health'
    | '/api/integrations/hbss/scans'
    | '/api/integrations/screening/suspect-events'
    | '/api/xray/bags/$bagId'
    | '/api/admin/roles/$roleId/permissions'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/repair-profile'
    | '/api/xray/bags/$bagId/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/alarms'
    | '/change-password'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/map'
    | '/readers'
    | '/recheck'
    | '/register'
    | '/reports'
    | '/simulator'
    | '/tagging'
    | '/target'
    | '/admin/dashboard'
    | '/audit/logs'
    | '/dev/api'
    | '/dev/console'
    | '/dev/db'
    | '/dev/events'
    | '/dev/flags'
    | '/dev/logs'
    | '/dev/simulator'
    | '/ops/scan'
    | '/settings/audit'
    | '/settings/escalations'
    | '/settings/map'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/threats'
    | '/settings/users'
    | '/supervisor/overview'
    | '/api/admin/users'
    | '/api/bags/pending-tagging'
    | '/api/bags/rfid-trackable'
    | '/api/admin/roles/permissions'
    | '/api/admin/users/$userId'
    | '/api/admin/users/invitations'
    | '/api/bags/$bagId/encode-tag'
    | '/api/dev/simulator/suspect-events'
    | '/api/integrations/hbss/health'
    | '/api/integrations/hbss/scans'
    | '/api/integrations/screening/suspect-events'
    | '/api/xray/bags/$bagId'
    | '/api/admin/roles/$roleId/permissions'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/repair-profile'
    | '/api/xray/bags/$bagId/refresh'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/alarms'
    | '/change-password'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/map'
    | '/readers'
    | '/recheck'
    | '/register'
    | '/reports'
    | '/simulator'
    | '/tagging'
    | '/target'
    | '/admin/dashboard'
    | '/audit/logs'
    | '/dev/api'
    | '/dev/console'
    | '/dev/db'
    | '/dev/events'
    | '/dev/flags'
    | '/dev/logs'
    | '/dev/simulator'
    | '/ops/scan'
    | '/settings/audit'
    | '/settings/escalations'
    | '/settings/map'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/threats'
    | '/settings/users'
    | '/supervisor/overview'
    | '/api/admin/users'
    | '/api/bags/pending-tagging'
    | '/api/bags/rfid-trackable'
    | '/api/admin/roles/permissions'
    | '/api/admin/users/$userId'
    | '/api/admin/users/invitations'
    | '/api/bags/$bagId/encode-tag'
    | '/api/dev/simulator/suspect-events'
    | '/api/integrations/hbss/health'
    | '/api/integrations/hbss/scans'
    | '/api/integrations/screening/suspect-events'
    | '/api/xray/bags/$bagId'
    | '/api/admin/roles/$roleId/permissions'
    | '/api/admin/users/$userId/actions'
    | '/api/admin/users/$userId/repair-profile'
    | '/api/xray/bags/$bagId/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AlarmsRoute: typeof AlarmsRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ReadersRoute: typeof ReadersRoute
  RecheckRoute: typeof RecheckRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SimulatorRoute: typeof SimulatorRoute
  TaggingRoute: typeof TaggingRoute
  TargetRoute: typeof TargetRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DevApiRoute: typeof DevApiRoute
  DevConsoleRoute: typeof DevConsoleRoute
  DevDbRoute: typeof DevDbRoute
  DevEventsRoute: typeof DevEventsRoute
  DevFlagsRoute: typeof DevFlagsRoute
  DevLogsRoute: typeof DevLogsRoute
  DevSimulatorRoute: typeof DevSimulatorRoute
  OpsScanRoute: typeof OpsScanRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsEscalationsRoute: typeof SettingsEscalationsRoute
  SettingsMapRoute: typeof SettingsMapRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThreatsRoute: typeof SettingsThreatsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SupervisorOverviewRoute: typeof SupervisorOverviewRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
  ApiBagsPendingTaggingRoute: typeof ApiBagsPendingTaggingRoute
  ApiBagsRfidTrackableRoute: typeof ApiBagsRfidTrackableRoute
  ApiAdminRolesPermissionsRoute: typeof ApiAdminRolesPermissionsRoute
  ApiBagsBagIdEncodeTagRoute: typeof ApiBagsBagIdEncodeTagRoute
  ApiDevSimulatorSuspectEventsRoute: typeof ApiDevSimulatorSuspectEventsRoute
  ApiIntegrationsHbssHealthRoute: typeof ApiIntegrationsHbssHealthRoute
  ApiIntegrationsHbssScansRoute: typeof ApiIntegrationsHbssScansRoute
  ApiIntegrationsScreeningSuspectEventsRoute: typeof ApiIntegrationsScreeningSuspectEventsRoute
  ApiXrayBagsBagIdRoute: typeof ApiXrayBagsBagIdRouteWithChildren
  ApiAdminRolesRoleIdPermissionsRoute: typeof ApiAdminRolesRoleIdPermissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagging': {
      id: '/tagging'
      path: '/tagging'
      fullPath: '/tagging'
      preLoaderRoute: typeof TaggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recheck': {
      id: '/recheck'
      path: '/recheck'
      fullPath: '/recheck'
      preLoaderRoute: typeof RecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers': {
      id: '/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof ReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/overview': {
      id: '/supervisor/overview'
      path: '/supervisor/overview'
      fullPath: '/supervisor/overview'
      preLoaderRoute: typeof SupervisorOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/threats': {
      id: '/settings/threats'
      path: '/settings/threats'
      fullPath: '/settings/threats'
      preLoaderRoute: typeof SettingsThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/map': {
      id: '/settings/map'
      path: '/settings/map'
      fullPath: '/settings/map'
      preLoaderRoute: typeof SettingsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/escalations': {
      id: '/settings/escalations'
      path: '/settings/escalations'
      fullPath: '/settings/escalations'
      preLoaderRoute: typeof SettingsEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/scan': {
      id: '/ops/scan'
      path: '/ops/scan'
      fullPath: '/ops/scan'
      preLoaderRoute: typeof OpsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/simulator': {
      id: '/dev/simulator'
      path: '/dev/simulator'
      fullPath: '/dev/simulator'
      preLoaderRoute: typeof DevSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/logs': {
      id: '/dev/logs'
      path: '/dev/logs'
      fullPath: '/dev/logs'
      preLoaderRoute: typeof DevLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/flags': {
      id: '/dev/flags'
      path: '/dev/flags'
      fullPath: '/dev/flags'
      preLoaderRoute: typeof DevFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/events': {
      id: '/dev/events'
      path: '/dev/events'
      fullPath: '/dev/events'
      preLoaderRoute: typeof DevEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/db': {
      id: '/dev/db'
      path: '/dev/db'
      fullPath: '/dev/db'
      preLoaderRoute: typeof DevDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/console': {
      id: '/dev/console'
      path: '/dev/console'
      fullPath: '/dev/console'
      preLoaderRoute: typeof DevConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/api': {
      id: '/dev/api'
      path: '/dev/api'
      fullPath: '/dev/api'
      preLoaderRoute: typeof DevApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/logs': {
      id: '/audit/logs'
      path: '/audit/logs'
      fullPath: '/audit/logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bags/rfid-trackable': {
      id: '/api/bags/rfid-trackable'
      path: '/api/bags/rfid-trackable'
      fullPath: '/api/bags/rfid-trackable'
      preLoaderRoute: typeof ApiBagsRfidTrackableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bags/pending-tagging': {
      id: '/api/bags/pending-tagging'
      path: '/api/bags/pending-tagging'
      fullPath: '/api/bags/pending-tagging'
      preLoaderRoute: typeof ApiBagsPendingTaggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xray/bags/$bagId': {
      id: '/api/xray/bags/$bagId'
      path: '/api/xray/bags/$bagId'
      fullPath: '/api/xray/bags/$bagId'
      preLoaderRoute: typeof ApiXrayBagsBagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/screening/suspect-events': {
      id: '/api/integrations/screening/suspect-events'
      path: '/api/integrations/screening/suspect-events'
      fullPath: '/api/integrations/screening/suspect-events'
      preLoaderRoute: typeof ApiIntegrationsScreeningSuspectEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/hbss/scans': {
      id: '/api/integrations/hbss/scans'
      path: '/api/integrations/hbss/scans'
      fullPath: '/api/integrations/hbss/scans'
      preLoaderRoute: typeof ApiIntegrationsHbssScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/hbss/health': {
      id: '/api/integrations/hbss/health'
      path: '/api/integrations/hbss/health'
      fullPath: '/api/integrations/hbss/health'
      preLoaderRoute: typeof ApiIntegrationsHbssHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/simulator/suspect-events': {
      id: '/api/dev/simulator/suspect-events'
      path: '/api/dev/simulator/suspect-events'
      fullPath: '/api/dev/simulator/suspect-events'
      preLoaderRoute: typeof ApiDevSimulatorSuspectEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bags/$bagId/encode-tag': {
      id: '/api/bags/$bagId/encode-tag'
      path: '/api/bags/$bagId/encode-tag'
      fullPath: '/api/bags/$bagId/encode-tag'
      preLoaderRoute: typeof ApiBagsBagIdEncodeTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/invitations': {
      id: '/api/admin/users/invitations'
      path: '/invitations'
      fullPath: '/api/admin/users/invitations'
      preLoaderRoute: typeof ApiAdminUsersInvitationsRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/api/admin/roles/permissions': {
      id: '/api/admin/roles/permissions'
      path: '/api/admin/roles/permissions'
      fullPath: '/api/admin/roles/permissions'
      preLoaderRoute: typeof ApiAdminRolesPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xray/bags/$bagId/refresh': {
      id: '/api/xray/bags/$bagId/refresh'
      path: '/refresh'
      fullPath: '/api/xray/bags/$bagId/refresh'
      preLoaderRoute: typeof ApiXrayBagsBagIdRefreshRouteImport
      parentRoute: typeof ApiXrayBagsBagIdRoute
    }
    '/api/admin/users/$userId/repair-profile': {
      id: '/api/admin/users/$userId/repair-profile'
      path: '/repair-profile'
      fullPath: '/api/admin/users/$userId/repair-profile'
      preLoaderRoute: typeof ApiAdminUsersUserIdRepairProfileRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/users/$userId/actions': {
      id: '/api/admin/users/$userId/actions'
      path: '/actions'
      fullPath: '/api/admin/users/$userId/actions'
      preLoaderRoute: typeof ApiAdminUsersUserIdActionsRouteImport
      parentRoute: typeof ApiAdminUsersUserIdRoute
    }
    '/api/admin/roles/$roleId/permissions': {
      id: '/api/admin/roles/$roleId/permissions'
      path: '/api/admin/roles/$roleId/permissions'
      fullPath: '/api/admin/roles/$roleId/permissions'
      preLoaderRoute: typeof ApiAdminRolesRoleIdPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAdminUsersUserIdRouteChildren {
  ApiAdminUsersUserIdActionsRoute: typeof ApiAdminUsersUserIdActionsRoute
  ApiAdminUsersUserIdRepairProfileRoute: typeof ApiAdminUsersUserIdRepairProfileRoute
}

const ApiAdminUsersUserIdRouteChildren: ApiAdminUsersUserIdRouteChildren = {
  ApiAdminUsersUserIdActionsRoute: ApiAdminUsersUserIdActionsRoute,
  ApiAdminUsersUserIdRepairProfileRoute: ApiAdminUsersUserIdRepairProfileRoute,
}

const ApiAdminUsersUserIdRouteWithChildren =
  ApiAdminUsersUserIdRoute._addFileChildren(ApiAdminUsersUserIdRouteChildren)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRouteWithChildren
  ApiAdminUsersInvitationsRoute: typeof ApiAdminUsersInvitationsRoute
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRouteWithChildren,
  ApiAdminUsersInvitationsRoute: ApiAdminUsersInvitationsRoute,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiXrayBagsBagIdRouteChildren {
  ApiXrayBagsBagIdRefreshRoute: typeof ApiXrayBagsBagIdRefreshRoute
}

const ApiXrayBagsBagIdRouteChildren: ApiXrayBagsBagIdRouteChildren = {
  ApiXrayBagsBagIdRefreshRoute: ApiXrayBagsBagIdRefreshRoute,
}

const ApiXrayBagsBagIdRouteWithChildren =
  ApiXrayBagsBagIdRoute._addFileChildren(ApiXrayBagsBagIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AlarmsRoute: AlarmsRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ReadersRoute: ReadersRoute,
  RecheckRoute: RecheckRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SimulatorRoute: SimulatorRoute,
  TaggingRoute: TaggingRoute,
  TargetRoute: TargetRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuditLogsRoute: AuditLogsRoute,
  DevApiRoute: DevApiRoute,
  DevConsoleRoute: DevConsoleRoute,
  DevDbRoute: DevDbRoute,
  DevEventsRoute: DevEventsRoute,
  DevFlagsRoute: DevFlagsRoute,
  DevLogsRoute: DevLogsRoute,
  DevSimulatorRoute: DevSimulatorRoute,
  OpsScanRoute: OpsScanRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsEscalationsRoute: SettingsEscalationsRoute,
  SettingsMapRoute: SettingsMapRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThreatsRoute: SettingsThreatsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SupervisorOverviewRoute: SupervisorOverviewRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiBagsPendingTaggingRoute: ApiBagsPendingTaggingRoute,
  ApiBagsRfidTrackableRoute: ApiBagsRfidTrackableRoute,
  ApiAdminRolesPermissionsRoute: ApiAdminRolesPermissionsRoute,
  ApiBagsBagIdEncodeTagRoute: ApiBagsBagIdEncodeTagRoute,
  ApiDevSimulatorSuspectEventsRoute: ApiDevSimulatorSuspectEventsRoute,
  ApiIntegrationsHbssHealthRoute: ApiIntegrationsHbssHealthRoute,
  ApiIntegrationsHbssScansRoute: ApiIntegrationsHbssScansRoute,
  ApiIntegrationsScreeningSuspectEventsRoute:
    ApiIntegrationsScreeningSuspectEventsRoute,
  ApiXrayBagsBagIdRoute: ApiXrayBagsBagIdRouteWithChildren,
  ApiAdminRolesRoleIdPermissionsRoute: ApiAdminRolesRoleIdPermissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
