/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetRouteImport } from './routes/target'
import { Route as TaggingRouteImport } from './routes/tagging'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecheckRouteImport } from './routes/recheck'
import { Route as ReadersRouteImport } from './routes/readers'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorOverviewRouteImport } from './routes/supervisor.overview'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsThreatsRouteImport } from './routes/settings.threats'
import { Route as SettingsSystemRouteImport } from './routes/settings.system'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsMapRouteImport } from './routes/settings.map'
import { Route as SettingsEscalationsRouteImport } from './routes/settings.escalations'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as OpsScanRouteImport } from './routes/ops.scan'
import { Route as DevConsoleRouteImport } from './routes/dev.console'
import { Route as AuditLogsRouteImport } from './routes/audit.logs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)
const TaggingRoute = TaggingRouteImport.update({
  id: '/tagging',
  path: '/tagging',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecheckRoute = RecheckRouteImport.update({
  id: '/recheck',
  path: '/recheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersRoute = ReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorOverviewRoute = SupervisorOverviewRouteImport.update({
  id: '/supervisor/overview',
  path: '/supervisor/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThreatsRoute = SettingsThreatsRouteImport.update({
  id: '/settings/threats',
  path: '/settings/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMapRoute = SettingsMapRouteImport.update({
  id: '/settings/map',
  path: '/settings/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEscalationsRoute = SettingsEscalationsRouteImport.update({
  id: '/settings/escalations',
  path: '/settings/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsScanRoute = OpsScanRouteImport.update({
  id: '/ops/scan',
  path: '/ops/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const DevConsoleRoute = DevConsoleRouteImport.update({
  id: '/dev/console',
  path: '/dev/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit/logs',
  path: '/audit/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/readers': typeof ReadersRoute
  '/recheck': typeof RecheckRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tagging': typeof TaggingRoute
  '/target': typeof TargetRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/audit/logs': typeof AuditLogsRoute
  '/dev/console': typeof DevConsoleRoute
  '/ops/scan': typeof OpsScanRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/escalations': typeof SettingsEscalationsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threats': typeof SettingsThreatsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/supervisor/overview': typeof SupervisorOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/readers': typeof ReadersRoute
  '/recheck': typeof RecheckRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tagging': typeof TaggingRoute
  '/target': typeof TargetRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/audit/logs': typeof AuditLogsRoute
  '/dev/console': typeof DevConsoleRoute
  '/ops/scan': typeof OpsScanRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/escalations': typeof SettingsEscalationsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threats': typeof SettingsThreatsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/supervisor/overview': typeof SupervisorOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/readers': typeof ReadersRoute
  '/recheck': typeof RecheckRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tagging': typeof TaggingRoute
  '/target': typeof TargetRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/audit/logs': typeof AuditLogsRoute
  '/dev/console': typeof DevConsoleRoute
  '/ops/scan': typeof OpsScanRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/escalations': typeof SettingsEscalationsRoute
  '/settings/map': typeof SettingsMapRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/threats': typeof SettingsThreatsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/supervisor/overview': typeof SupervisorOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/map'
    | '/readers'
    | '/recheck'
    | '/register'
    | '/reports'
    | '/simulator'
    | '/tagging'
    | '/target'
    | '/admin/dashboard'
    | '/audit/logs'
    | '/dev/console'
    | '/ops/scan'
    | '/settings/audit'
    | '/settings/escalations'
    | '/settings/map'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/threats'
    | '/settings/users'
    | '/supervisor/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/map'
    | '/readers'
    | '/recheck'
    | '/register'
    | '/reports'
    | '/simulator'
    | '/tagging'
    | '/target'
    | '/admin/dashboard'
    | '/audit/logs'
    | '/dev/console'
    | '/ops/scan'
    | '/settings/audit'
    | '/settings/escalations'
    | '/settings/map'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/threats'
    | '/settings/users'
    | '/supervisor/overview'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/forgot-password'
    | '/history'
    | '/login'
    | '/map'
    | '/readers'
    | '/recheck'
    | '/register'
    | '/reports'
    | '/simulator'
    | '/tagging'
    | '/target'
    | '/admin/dashboard'
    | '/audit/logs'
    | '/dev/console'
    | '/ops/scan'
    | '/settings/audit'
    | '/settings/escalations'
    | '/settings/map'
    | '/settings/roles'
    | '/settings/system'
    | '/settings/threats'
    | '/settings/users'
    | '/supervisor/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ReadersRoute: typeof ReadersRoute
  RecheckRoute: typeof RecheckRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SimulatorRoute: typeof SimulatorRoute
  TaggingRoute: typeof TaggingRoute
  TargetRoute: typeof TargetRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DevConsoleRoute: typeof DevConsoleRoute
  OpsScanRoute: typeof OpsScanRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsEscalationsRoute: typeof SettingsEscalationsRoute
  SettingsMapRoute: typeof SettingsMapRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsThreatsRoute: typeof SettingsThreatsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SupervisorOverviewRoute: typeof SupervisorOverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tagging': {
      id: '/tagging'
      path: '/tagging'
      fullPath: '/tagging'
      preLoaderRoute: typeof TaggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recheck': {
      id: '/recheck'
      path: '/recheck'
      fullPath: '/recheck'
      preLoaderRoute: typeof RecheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers': {
      id: '/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof ReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/overview': {
      id: '/supervisor/overview'
      path: '/supervisor/overview'
      fullPath: '/supervisor/overview'
      preLoaderRoute: typeof SupervisorOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/threats': {
      id: '/settings/threats'
      path: '/settings/threats'
      fullPath: '/settings/threats'
      preLoaderRoute: typeof SettingsThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/map': {
      id: '/settings/map'
      path: '/settings/map'
      fullPath: '/settings/map'
      preLoaderRoute: typeof SettingsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/escalations': {
      id: '/settings/escalations'
      path: '/settings/escalations'
      fullPath: '/settings/escalations'
      preLoaderRoute: typeof SettingsEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/scan': {
      id: '/ops/scan'
      path: '/ops/scan'
      fullPath: '/ops/scan'
      preLoaderRoute: typeof OpsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/console': {
      id: '/dev/console'
      path: '/dev/console'
      fullPath: '/dev/console'
      preLoaderRoute: typeof DevConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/logs': {
      id: '/audit/logs'
      path: '/audit/logs'
      fullPath: '/audit/logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ReadersRoute: ReadersRoute,
  RecheckRoute: RecheckRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SimulatorRoute: SimulatorRoute,
  TaggingRoute: TaggingRoute,
  TargetRoute: TargetRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuditLogsRoute: AuditLogsRoute,
  DevConsoleRoute: DevConsoleRoute,
  OpsScanRoute: OpsScanRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsEscalationsRoute: SettingsEscalationsRoute,
  SettingsMapRoute: SettingsMapRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsThreatsRoute: SettingsThreatsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SupervisorOverviewRoute: SupervisorOverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
